name = "SymmetricOrthogonalPolynomials"
uuid = "fc9a72a9-1ea7-43f9-8932-c79acf841176"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.1.0"

[deps]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
RepresentationTheory = "6b7c1d51-ecee-4149-97a8-50646b514dce"
